# Build pipeline for az login .
# add more az cli commands after line # 21 to create more reosurces like VM , subnets, ips, etc..

trigger:
- master

pool:
  vmImage: 'windows-latest'
steps:
  # Sample command to test echo
  - script: echo This is a build pipeline using Azure-pipelines
  # This is a sample command to test mkdir
  - script: md sampledir
  # This is a sample command to create a file
  - script: echo "abcedef" >> c:\cred.txt
  # Actual script needed for you.
  - script: |
        dir 
        az login --service-principal --username "3d587273-dcac-47f1-b714-72f244c67c52"  --password "8ec3a20c-e55e-4341-abec-28d57eab3be1" --tenant "59b2865a-7fb8-4ccb-ab68-72cbca88fc48"
        echo After Login
        az resource list --out table > data2.txt 2>&1
        echo After Resource List
  - script: |      
        dir /od
        echo  After resource List
        type data2.txt
        dir
        
# {
#  "appId": "3d587273-dcac-47f1-b714-72f244c67c52A",
#  "displayName": "ServicePrincipalName1",
#  "name": "http://ServicePrincipalName1",
#  "password": "8ec3a20c-e55e-4341-abec-28d57eab3be1B",
#  "tenant": "59b2865a-7fb8-4ccb-ab68-72cbca88fc48C"
# }
# az login --service-principal --username APP_ID --password PASSWORD --tenant TENANT_ID
# This command used hte appId password and tenat generated by command "az ad sp create-for-rbac --name ServicePrinicpleName". Sample output generate by this command is pasted at line #22
# The above command will only get executed after the manual 'az login'

