# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'
steps:
  - script: echo hello from Windows with a change in the line
  - script: md sampledir
  - script: echo "Veriz@1" >> c:\cred.txt
  - script: |
        dir /od 
        dir
        az login --service-principal --username "3d587273-dcac-47f1-b714-72f244c67c52"  --password "8ec3a20c-e55e-4341-abec-28d57eab3be1" --tenant "59b2865a-7fb8-4ccb-ab68-72cbca88fc48"
        az resource list
#{
#  "appId": "3d587273-dcac-47f1-b714-72f244c67c52A",
#  "displayName": "ServicePrincipalName1",
#  "name": "http://ServicePrincipalName1",
#  "password": "8ec3a20c-e55e-4341-abec-28d57eab3be1B",
#  "tenant": "59b2865a-7fb8-4ccb-ab68-72cbca88fc48C"
#}
# az login --service-principal --username APP_ID --password PASSWORD --tenant TENANT_ID
